spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb+srv://dubovayaalena:q2TNvWj90XDiQYY2@musica-project-db.er2rtlm.mongodb.net/?retryWrites=true&w=majority&appName=Musica-project-db
spring.data.mongodb.database=sample_mflix